apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculties-deployment
spec:
  replicas: 1                         # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: faculties                # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
     labels:
       app: faculties               # мітка Pod по якому вона буде зв'язана з Deployment та Service


    spec:
      containers:
        - image: faculties:01     # образ Docker
          imagePullPolicy: Never      # вказує k8s, що образ не потрібно завантажувати (варто використовувати лише для випадків, коли образи локальні)
          name: faculties           # ім'я контейнеру
          ports:
            - containerPort: 80     # порт по якому можна звертатись до 
          envFrom:
            - configMapRef:
                name: faculties-config
            - secretRef:
                name: faculties-secret
