apiVersion: batch/v1
kind: Job
metadata:
  name: migration-faculties-postgres
spec:
  template:
    spec:
      containers:
        - name: migration-faculties-postgres
          image: voonya/migration-auth-db
          imagePullPolicy: Always
          command: [ 'dotnet', 'ef', 'database', 'update' ]
          envFrom:
            - configMapRef:
                name: faculty-config
            - secretRef:
                name: faculty-secret
          env:
            - name: DB_URL
              value: "$(DB_DIALECT)://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
      restartPolicy: Never
  backoffLimit: 0