apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculties-mssql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faculties-mssql
  template:
    metadata:
      labels:
        app: faculties-mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql
                key: SA_PASSWORD
          volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: facultiesdb
      volumes:
      - name: facultiesdb
        persistentVolumeClaim:
          claimName: faculties-mssql-claim