apiVersion: apps/v1
kind: Deployment
metadata:
  name: specialties-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: specialties-postgres
  template:
    metadata:
      labels:
        app: specialties-postgres
    spec:
      containers:
        - name: specialties-postgres
          image: postgres:14.1-alpine3.15
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: specialties-postgres-config
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: specialtiesservice
      volumes:
        - name: specialtiesservice
          persistentVolumeClaim:
            claimName: specialties-postgres-pv-claim

        