# Default values for tasks-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgresql:
  fullnameOverride: teachers-postgres
  postgresqlDatabase: "teachersservice"
  postgresqlUsername: "postgresadmin"
  postgresqlPassword: "admin123"
  persistence:
    size: 1Gi
    mountPath: /var/lib/postgresql/data

container:
  name: teachers

image:
  name: hurmaze/teachers
  tag: latest

service:
  ports:
    - name: app
      port: 80
      containerPort: 80

ingress:
  path: /api/teachers
  port: app

config:
  data:
    PORT: "8080"
    POSTGRES_DB: teachersservice
    DB_HOST: teachers-postgres
    DB_DIALECT: postgres
    DB_PORT: "5432"

secret:
  stringData:
    TEACHERS_DB_URL: "postgresql://demo:demo@teachers-postgres:5432/teachers?sslmode=disable"
    DB_NAME: dGVhY2hlcnNzZXJ2aWNl
    DB_USERNAME: cG9zdGdyZXNhZG1pbg==
    DB_PASSWORD: YWRtaW4xMjM=

secretMounts:
  mountPath: /app/build/helpers/keys
  paths:
    DB_NAME: dGVhY2hlcnNzZXJ2aWNl
    DB_USERNAME: cG9zdGdyZXNhZG1pbg==
    DB_PASSWORD: YWRtaW4xMjM=