# Default values for tasks-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgresql:
  fullnameOverride: specialties-postgres
  postgresqlDatabase: "specialtiesservice"
  postgresqlUsername: "postgresadmin"
  postgresqlPassword: "admin123"
  persistence:
    size: 1Gi
    mountPath: /var/lib/postgresql/data

container:
  name: specialties

image:
  name: hurmaze/specialties
  tag: latest

service:
  ports:
    - name: app
      port: 3000
      containerPort: 3000

ingress:
  path: "/api/specialties/v1(/|$)(.*)"
  port: app
  pathRewrite: "/$2"

secret:
  stringData:
    SPECIALTIES_DB_URL: "postgresql://demo:demo@specialties-postgres:5432/specialties?sslmode=disable"
    DB_NAME: dGVhY2hlcnNzZXJ2aWNl
    DB_USERNAME: cG9zdGdyZXNhZG1pbg==
    DB_PASSWORD: YWRtaW4xMjM=

secretMounts:
  mountPath: /app/build/helpers/keys
  paths:
    PUBLIC_KEY: public.txt