apiVersion: v1
kind: ConfigMap
metadata:
  name: faculties-postgres-config
  labels:
    app: faculties-postgres
data:
  POSTGRES_DB: facultiesservice
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123