export const environment = {
  production: true,
  facultyUrl: 'api/faculties',
  teachersUrl: 'api/teachers',
  specialtiesUrl: 'api/specialties',
  disciplinesUrl: 'api/disciplines',
  catalogsUrl: 'api/disciplines/catalogs',
  groupsUrl: 'api/groups',
  catalogDisciplinesUrl: 'api/disciplines/catalogDisciplines',
  disciplineTeachersUrl: 'api/disciplines/disciplineTeachers',
  specialtyDisciplinesUrl: 'api/disciplines/specialtyDisciplines',
  facultySpecialtyUrl: 'api/specialties/facultySpecialties',
  facultyDisciplineUrl: 'api/disciplines/facultyDisciplines',
  facultyTeacherUrl: 'api/teachers/facultyTeachers',
  whiteListedDomains: [''],
  usersUrl: 'api/tokens',
  urlPrefix: 'http://192.168.59.120/',
};
